//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanXeGanMayEntities : DbContext
    {
        public QLBanXeGanMayEntities()
            : base("name=QLBanXeGanMayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDONTHANG> CHITIETDONTHANG { get; set; }
        public DbSet<DONDATHANG> DONDATHANG { get; set; }
        public DbSet<HANGSANXUAT> HANGSANXUAT { get; set; }
        public DbSet<KHACHHANG> KHACHHANG { get; set; }
        public DbSet<LOAIXE> LOAIXE { get; set; }
        public DbSet<NHAPHANPHOI> NHAPHANPHOI { get; set; }
        public DbSet<SANXUATXE> SANXUATXE { get; set; }
        public DbSet<XEGANMAY> XEGANMAY { get; set; }
        public DbSet<Admin> Admin { get; set; }
    }
}
